- NAME: server1
  hostname: server1.com
  ipaddr: 10.87.49.74
- NAME: server2
  hostname: server2.com
  ipaddr: 55.55.55.11111
- NAME: server3
  hostname: server3.com
  ipaddr: 12.42.1.2
- NAME: server4
  hostname: server4.com
  ipaddr: 10.42.52.6
